# -*- coding: utf-8 -*-
"""Cartas

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NGyMgzJxd8Vl93k3HbiusF_c9gUwTG-Z
"""

Lpalos=["♣","♥","♦","♠"]
Lnumeros=["Nada","1","2","3","4","5","6","7","8","9","10","J","Q","K"]

class Carta():

    def __init__(self,numero=1,palo=1):
        self.numero=numero
        self.palo=palo
    def __str__(self):
        return(Lnumeros[self.numero]+" de " +Lpalos[self.palo])
    def __cmp__(self,otro):
        if int(self.palo) > int(otro.palo): return (1)
        if int(self.palo) < int(otro.palo): return (-1)
        if int(self.numero) > int(otro.numero): return (1)
        if int(self.numero) < int(otro.numero): return (-1)
        return (0)
    def __eq__(self,otro):
      return (self.palo == otro.palo and self.numero == otro.numero)
  
class Mazo():
  def __init__(self):
    self.cartas=[]
    for palo in range(4):
      for num in range(1,14):
        self.cartas.append(Carta(num,palo))
  def muestra(self):
    i = 0
    s =" "
    for carta in self.cartas:
      print(s*i+str(carta))
      i = i+1

  
mazo1=Mazo()
mazo1.muestra()